CREATE SEQUENCE IF NOT EXISTS cart_seq
MINVALUE 100
START WITH 100
INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS cart
(
    id      INTEGER PRIMARY KEY,
    user_id INTEGER UNIQUE NOT NULL
);

ALTER SEQUENCE cart_seq OWNED BY cart.id;